version: '3'

services:
  service-db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: TestPassword12345
    ports:
      - "15432:5432"
    restart: unless-stopped

  client-backend:
    image: storageserver:0.0.2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - service-db
    environment:
      - SERVER_PORT= 8001
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db/postgres

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: parfenovartemartem@yandex.ru
      PGADMIN_DEFAULT_PASSWORD: Artemotlichnic5
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  db-data:
  pgadmin-data: